/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacyControlar;

import Com.modelpackage.AgentsModel;
import Service.AgentsService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Azam
 */
public class Agents extends javax.swing.JFrame {
    String id;
    String name;
    int age;
    String phone;
    String password;
    String gender;

    /**
     * Creates new form Agents
     */
    public Agents() {
        initComponents();
         List<AgentsModel> l = new AgentsService().getAll(null);
          DefaultTableModel n = (DefaultTableModel) jtaagen.getModel();
          n.setRowCount(0);
          //stem.out.println(l.get(0).getaName());
        for (int i = 0; i < l.size(); i++) {
            AgentsModel get = l.get(i);
            n.addRow(new Object[] {get.getaId(),get.getaName(),get.getAge(),get.getPhone(),
            get.getApassword(),get.getGender()});
        }
    }
    private void getallagens(){
   id = aId.getText();
   name = aname.getText();
   age = Integer.parseInt(aage.getText());
   phone = aphone.getText();
   password = apassword.getText();
   gender = agender.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aname = new javax.swing.JTextField();
        aId = new javax.swing.JTextField();
        agender = new javax.swing.JComboBox<>();
        aupdatebtn = new javax.swing.JButton();
        aserchbtn = new javax.swing.JButton();
        aaddbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaagen = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        aage = new javax.swing.JTextField();
        aphone = new javax.swing.JTextField();
        apassword = new javax.swing.JPasswordField();
        adeletebtn = new javax.swing.JButton();
        acleanbtn1 = new javax.swing.JButton();
        idserch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 0));
        jLabel5.setText("MANAGE AGENTS");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("    ID:");
        jLabel6.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel6InputMethodTextChanged(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 97, 47, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("NAME:");
        jLabel7.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel7InputMethodTextChanged(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 131, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("      AGE:");
        jLabel8.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel8InputMethodTextChanged(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 78, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("PHONE:");
        jLabel10.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel10InputMethodTextChanged(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 99, 81, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("PASSWORD:");
        jLabel11.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel11InputMethodTextChanged(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 150, 89, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("GENDER:");
        jLabel12.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel12InputMethodTextChanged(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 181, 81, -1));

        aname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aname.setForeground(new java.awt.Color(255, 102, 102));
        jPanel3.add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 126, 159, 28));

        aId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aId.setForeground(new java.awt.Color(255, 102, 102));
        jPanel3.add(aId, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 92, 159, 28));

        agender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        agender.setForeground(new java.awt.Color(255, 102, 102));
        agender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(agender, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 174, 151, -1));

        aupdatebtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aupdatebtn.setForeground(new java.awt.Color(255, 102, 102));
        aupdatebtn.setText("Update");
        aupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aupdatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(aupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        aserchbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aserchbtn.setForeground(new java.awt.Color(255, 102, 102));
        aserchbtn.setText("SHERCH");
        aserchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aserchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(aserchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        aaddbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aaddbtn.setForeground(new java.awt.Color(255, 102, 102));
        aaddbtn.setText("Add");
        aaddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaddbtnActionPerformed(evt);
            }
        });
        jPanel3.add(aaddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jtaagen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "AGE", "PHONE", "PASSWORD", "GENDER"
            }
        ));
        jtaagen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaagenKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtaagen);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 525, 290));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 0));
        jLabel13.setText("AGENTS LIST");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        aage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aage.setForeground(new java.awt.Color(255, 102, 102));
        jPanel3.add(aage, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 174, 159, 28));

        aphone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aphoneActionPerformed(evt);
            }
        });
        jPanel3.add(aphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 92, 151, -1));

        apassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(apassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 146, 151, -1));

        adeletebtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adeletebtn.setForeground(new java.awt.Color(255, 102, 102));
        adeletebtn.setText("Delete");
        adeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adeletebtnActionPerformed(evt);
            }
        });
        jPanel3.add(adeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        acleanbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        acleanbtn1.setForeground(new java.awt.Color(255, 102, 102));
        acleanbtn1.setText("CLEAR");
        jPanel3.add(acleanbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        idserch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(idserch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 0, 914, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("COMPANY");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 178, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEDICIENS");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 218, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELLING");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 258, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel6InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6InputMethodTextChanged

    private void jLabel7InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel7InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7InputMethodTextChanged

    private void jLabel8InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel8InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8InputMethodTextChanged

    private void jLabel10InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel10InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10InputMethodTextChanged

    private void jLabel11InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel11InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11InputMethodTextChanged

    private void jLabel12InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel12InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12InputMethodTextChanged

    private void aphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aphoneActionPerformed

    private void aaddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaddbtnActionPerformed
        // TODO add your handling code here:
        getallagens();
        AgentsModel amodl = new AgentsModel();
        amodl.setaId(id);
        amodl.setaName(name);
        amodl.setAge(age);
        amodl.setPhone(phone);
        amodl.setApassword(password);
        amodl.setGender(gender);
        int st = new AgentsService().save(amodl);
        if(st>0){
            JOptionPane.showMessageDialog(rootPane, "DAta Save");
         List<AgentsModel> l = new Service.AgentsService().getAll(null);
          DefaultTableModel n = (DefaultTableModel) jtaagen.getModel();
          n.setRowCount(0);
            //System.out.println(l.get(0).getaName());
        for (int i = 0; i < l.size(); i++) {
            AgentsModel get = l.get(i);
            n.addRow(new Object[] {get.getaId(),get.getaName(),get.getAge(),get.getPhone(),
            get.getApassword(),get.getGender()});
        }
        
        }else{
        JOptionPane.showMessageDialog(rootPane, "Data not Save");
        }
    }//GEN-LAST:event_aaddbtnActionPerformed

    private void aserchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aserchbtnActionPerformed
        // TODO add your handling code here:
        //ge tallagens();
        String setex = idserch.getText();
        //int sets = Integer.parseInt(idserch.getText());
        AgentsModel serc = new AgentsModel();
        serc.setaId(setex);
        AgentsModel se = new AgentsService().search(serc);
        aId.setText(se.getaId());
        aname.setText(se.getaName());
        aage.setText(String.valueOf(se.getAge()));
        aphone.setText(se.getPhone());
        apassword.setText(se.getApassword());
        agender.setSelectedItem(se.getGender());
        
    }//GEN-LAST:event_aserchbtnActionPerformed

    private void aupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aupdatebtnActionPerformed
        // TODO add your handling code here:
        getallagens();
        AgentsModel up = new AgentsModel();
        up.setaId(id);
        up.setaName(name);
        up.setAge(age);
        up.setPhone(phone);
        up.setApassword(password);
        up.setGender(gender);
        int st = new AgentsService().update(up);
        if(st>0){
            JOptionPane.showMessageDialog(rootPane, "DAta Update");
             List<AgentsModel> l = new Service.AgentsService().getAll(null);
          DefaultTableModel n = (DefaultTableModel) jtaagen.getModel();
          n.setRowCount(0);
            //System.out.println(l.get(0).getaName());
        for (int i = 0; i < l.size(); i++) {
            AgentsModel get = l.get(i);
            n.addRow(new Object[] {get.getaId(),get.getaName(),get.getAge(),get.getPhone(),
            get.getApassword(),get.getGender()});
        }
            
        
        }else{
        JOptionPane.showMessageDialog(rootPane, "Data not Update");
        }
        
    }//GEN-LAST:event_aupdatebtnActionPerformed

    private void adeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adeletebtnActionPerformed
        // TODO add your handling code here:
        getallagens();
        AgentsModel de = new AgentsModel();
        de.setaId(id);
        int st = new AgentsService().delete(de);
        if(st>0){
            JOptionPane.showMessageDialog(rootPane, "DAta Delete");
         List<AgentsModel> l = new Service.AgentsService().getAll(null);
          DefaultTableModel n = (DefaultTableModel) jtaagen.getModel();
          n.setRowCount(0);
            //System.out.println(l.get(0).getaName());
        for (int i = 0; i < l.size(); i++) {
            AgentsModel get = l.get(i);
            n.addRow(new Object[] {get.getaId(),get.getaName(),get.getAge(),get.getPhone(),
            get.getApassword(),get.getGender()});
        }
        }else{
        JOptionPane.showMessageDialog(rootPane, "Data not Delete");
        }
    }//GEN-LAST:event_adeletebtnActionPerformed

    private void jtaagenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaagenKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtaagenKeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Company().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Medicine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aId;
    private javax.swing.JButton aaddbtn;
    private javax.swing.JTextField aage;
    private javax.swing.JButton acleanbtn1;
    private javax.swing.JButton adeletebtn;
    private javax.swing.JComboBox<String> agender;
    private javax.swing.JTextField aname;
    private javax.swing.JPasswordField apassword;
    private javax.swing.JTextField aphone;
    private javax.swing.JButton aserchbtn;
    private javax.swing.JButton aupdatebtn;
    private javax.swing.JTextField idserch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtaagen;
    // End of variables declaration//GEN-END:variables
}
